### ISSUE TITLE
Adapter fails to open after update JS controller to 3.1.6

### ISSUE THREAD

**Issue by dilmash** [ioBroker/ioBroker.cul#14]
After updating js controller to 3.1.6 (from 3.1.4) the cul adapter failed to find the serial device.

Message:
`SerialPort.list no longer takes a callback and only returns a promise`

```
cul.0 | 2020-07-15 15:13:19.737 | error | at processImmediate (internal/timers.js:456:21)
cul.0 | 2020-07-15 15:13:19.737 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:234:41)
cul.0 | 2020-07-15 15:13:19.737 | error | at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5313:34)
cul.0 | 2020-07-15 15:13:19.737 | error | at Adapter.emit (events.js:315:20)
cul.0 | 2020-07-15 15:13:19.737 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.cul/main.js:105:40)
cul.0 | 2020-07-15 15:13:19.737 | error | at Function.SerialPort.list (/opt/iobroker/node_modules/iobroker.cul/node_modules/serialport/node_modules/@serialport/stream/lib/index.js:651:11)
cul.0 | 2020-07-15 15:13:19.737 | error | (2267) TypeError: SerialPort.list no longer takes a callback and only returns a promise
cul.0 | 2020-07-15 15:13:19.725 | error | (2267) unhandled promise rejection: SerialPort.list no longer takes a callback and only returns a promise
Unhandled | 2020-07-15 15:13:19.723 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
```

**Comment by Apollon77** [comment]
This has nothing to do with js-controller update! You use the GitHub version of the adapter ... and thids is brokern. Use the 1.2.1 from latest repository please
